# Generated by Django 3.0.5 on 2021-02-13 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuPairUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('agency', models.CharField(max_length=255)),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='create_dt')),
                ('modified_dt', models.DateTimeField(auto_now=True, verbose_name='modified_dt')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuPairInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('town', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=30)),
                ('zipcode', models.CharField(max_length=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='restauth.AuPairUser')),
            ],
        ),
    ]
