# Generated by Django 3.0.5 on 2021-03-07 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restauth', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuPairInfo',
            new_name='AuPairProfile',
        ),
        migrations.AddField(
            model_name='aupairuser',
            name='staff',
            field=models.BooleanField(default=False),
        ),
    ]
