# Generated by Django 3.1.6 on 2021-02-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aupairuser',
            name='zipcode',
            field=models.IntegerField(max_length=5),
        ),
    ]
