# Generated by Django 3.1.6 on 2021-02-11 08:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restauth', '0002_auto_20210211_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aupairuser',
            name='zipcode',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99999)]),
        ),
    ]
