# Generated by Django 3.1.6 on 2021-02-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restauth', '0003_auto_20210211_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aupairuser',
            name='zipcode',
            field=models.CharField(max_length=5),
        ),
    ]
